# -*- coding: utf-8 -*-
"""prototype.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpH2kpkj9sf0ViO85FrVN8n0zsvERcWi
"""

!pip install -q transformers[torch]

from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

"""# Summarization example

"""

summarizer = pipeline("summarization", model="lcw99/t5-large-korean-text-summary")

"""
# Setiment analysis example"""

checkpoint = "Hyeonseo/ko-finance_news_classifier"

classifier = pipeline("sentiment-analysis", model=checkpoint)

"""부정/긍정/중립 출력확인

#Keyword extraction example
"""

tokenizer = AutoTokenizer.from_pretrained("Leo97/KoELECTRA-small-v3-modu-ner")
model = AutoModelForTokenClassification.from_pretrained("Leo97/KoELECTRA-small-v3-modu-ner")
ner = pipeline("ner", model=model, tokenizer=tokenizer)

"""# Pipeline"""

long_input = '5일부터 7일까지 3일간 입찰…8일 발표한국자산관리공사(캠코)가 5일부터 7일까지 3일간 온비드를 통해 1196억원 규모의 압류재산 1099건을 공매한다.압류재산 공매는 세무서 및 지방자치단체 등 공공기관이 국세·지방세 등의 체납세액 징수를 위해 압류한 재산을 캠코를 통해 매각하는 행정절차다.공매는 토지, 주택 등 부동산과 자동차, 귀금속, 유가증권 등 압류 가능한 모든 물품을 대상으로 진행된다. 회차별 공매 물건은 온비드 홈페이지 내 ‘부동산 또는 동산 > 공고 > 캠코 압류재산’에서 확인할 수 있다.이번 공매에는 부동산 990건, 동산 109건이 매각된다. 이 중 임야 등 토지가 601건으로 가장 많다. 아파트, 주택 등 주거용 건물도 서울, 경기 등 수도권 소재 물건 67건을 포함해 총 124건이 공매된다. 자동차, 귀금속 등 동산도 매각된다. 전체 물건 중 감정가의 70% 이하인 물건도 645건 포함됐다.다만 공매 입찰 시에는 권리분석에 유의해야 하고, 임차인에 대한 명도책임은 매수자에게 있으므로 주의를 기울여야 한다. 세금납부, 송달불능 등 사유로 입찰 전에 해당 물건 공매가 취소될 수도 있다. 입찰 전 공부 열람, 현장 조사 등을 통해 입찰을 희망하는 물건에 대해 상세히 확인하고 입찰에 참여해야 한다.캠코의 압류재산 공매는 온비드 또는 스마트온비드 애플리케이션(앱)을 통해 입찰 가능하다. 차수별 2주 간격으로 입찰이 진행되고, 유찰될 경우 공매예정가격이 10% 차감된다.'
short_input = summarizer(long_input)
print(short_input)

polarity = classifier(short_input[0]['summary_text'])
print(polarity)

# pipeline
ner_results = ner(short_input[0]['summary_text'])

ogs = []
for _ in ner_results:
  if _['entity'] in ['B-OG']:
    og = _['word']
  elif _['entity'] in ['I-OG']:
    og += _['word'][2:]
  else:
    ogs.append(og)
else:
  ogs.append(og)

print(og)

